
name: Pull Request

on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo -e "\033[31;1;4mDump GitHub context\033[0m"
          echo -e "$GITHUB_CONTEXT\n"
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install Node
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: NX Git environment setup
        uses: nrwl/nx-set-shas@v3
          with:
            # The "main" branch of your repository (the base branch which you target with PRs).
            # Common names for this branch include main and master.
            #
            # Default: main
            main-branch-name: 'master'
      - name: Restore Cache
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Install dependencies
        run: yarn install --ignore-platform
      - name: Create Cache Directory
        run: mkdir /home/runner/work/ngrid/ngrid/.cache
      - name: Test
        run: ./node_modules/.bin/nx affected:test --configuration=ci
      - name: Build Libraries
        run: npm run build-grid
      - name: E2E
        run: ./node_modules/.bin/nx affected:e2e --configuration=production-dist
      - name: E2E Upload Artifacts
        if: failure()
        uses: actions/upload-artifact@v2
        with:
          name: cypress-artifacts
          path: dist/cypress/**/*.png
          retention-days: 30
      - name: Build Libraries (IVY)
        run: npm run build-grid:ivy
