
name: Pull Request

on:
  workflow_dispatch:
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          ref: v3
      - name: Install Node
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Restore Cache
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Install dependencies
        run: npm install
      - run: mkdir /home/runner/work/ngrid/ngrid/.cache
      - name: Test
        run: ./node_modules/.bin/nx affected:test --base=origin/master --head=${{ github.ref }} --configuration=ci
        # run: ./node_modules/.bin/nx test --configuration=ci
      - name: E2E
        run: ./node_modules/.bin/nx affected:e2e --base=origin/master --head=${{ github.ref }}
        # run: ./node_modules/.bin/nx e2e
      - name: Build Libraries
        run: npm run build-grid
